openapi: 3.1.0
info:
  title: ServiceQualification
  version: '1.0'
  summary: Service Qualification API
  description: 'Service Qualification API is used to validate the address qualification, if address is qualified need to call pending order api to check address is having existing service or not'
  contact:
    name: Gaurav
    email: gaurav.khandelwal@brightspeed.com
servers:
  - url: 'https://brightspeed-np-dev.apigee.net'
paths:
  /dev-address-qualification:
    parameters: []
    get:
      summary: Service Avalibility
      tags: []
      responses:
        '200':
          description: Different response based on scenerio.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/User'
              examples:
                AddressQualified:
                  value:
                    errorCode: 0
                    errorText: Success
                    fullAddress: 940 FIRST ST MANTEO NC 27954
                    addressId: 40b73544650ab176bad928638e341ed2
                    latitude: '35.91777'
                    longitude: '-75.679993'
                    brightSpeedFiberIndicator: Qualified
                    interval: +1 day
                    existingService: false
                    pendingOrder: false
                InValidAddress:
                  value:
                    errorCode: 3003
                    errorText: Invalid Address
                    fullAddress: ''
                    addressId: ''
                    latitude: ''
                    longitude: ''
                    brightSpeedFiberIndicator: Not Qualified
                    interval: ''
                    existingService: false
                    pendingOrder: false
                ExistingService:
                  value:
                    errorCode: 3001
                    errorText: Active service available
                    fullAddress: 940 FIRST ST MANTEO NC 27954
                    addressId: 40b73544650ab176bad928638e341ed2
                    latitude: '35.91777'
                    longitude: '-75.679993'
                    brightSpeedFiberIndicator: Qualified
                    interval: +1 day
                    existingService: true
                    pendingOrder: false
        '201':
          description: Created
        '400':
          description: Bad Request
        '404':
          description: User Not Found
      operationId: ''
      description: Used to check service availibility
      parameters:
        - schema:
            type: string
          in: query
          name: addressLine1
          description: Full address
        - schema:
            type: string
          in: header
          name: Authorization
  '':
    parameters: []
components:
  schemas:
    User:
      title: ServiceQualification
      type: object
      description: Service Qualification query parameter
      examples:
        - errorCode: 0
          errorText: Success
          fullAddress: 940 FIRST ST MANTEO NC 27954
          addressId: 40b73544650ab176bad928638e341ed2
          latitude: '35.91777'
          longitude: '-75.679993'
          brightSpeedFiberIndicator: Qualified
          interval: +1 day
          existingService: false
          pendingOrder: false
      properties:
        addressLine1:
          type: string
