openapi: 3.1.0
x-stoplight:
  id: 591mscm5jf6tg
info:
  title: TechAppointmentApi
  version: '1.0'
  summary: Used to create and book slot
servers:
  - url: 'http://localhost:3000'
paths:
  /createappointment:
    parameters: []
    post:
      summary: ''
      operationId: post-CreateAppointment
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  messageType:
                    type: string
                  message:
                    type: string
                  data:
                    type: array
                    items:
                      type: object
                      properties:
                        slotStart:
                          type: string
                        slotEnd:
                          type: string
                        grade:
                          type: integer
                x-examples:
                  example-1:
                    messageType: success
                    message: success
                    data:
                      - slotStart: '2022-04-01T15:00:00.000Z'
                        slotEnd: '2022-04-02T00:00:00.000Z'
                        grade: 100
                      - slotStart: '2022-04-04T15:00:00.000Z'
                        slotEnd: '2022-04-05T00:00:00.000Z'
                        grade: 100
              examples:
                CreateSlot:
                  value:
                    messageType: success
                    message: success
                    data:
                      - slotStart: '2022-06-03T09:00:00.000Z'
                        slotEnd: '2022-06-03T11:00:00.000Z'
                        grade: 100
                      - slotStart: '2022-06-03T11:00:00.000Z'
                        slotEnd: '2022-06-03T13:00:00.000Z'
                        grade: 100
                      - slotStart: '2022-06-03T14:00:00.000Z'
                        slotEnd: '2022-06-03T16:00:00.000Z'
                        grade: 100
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                workOrder:
                  type: object
                  properties:
                    workTypeName:
                      type: string
                    serviceTerritoryName:
                      type: string
                    recordTypeName:
                      type: string
                    DC_Appointment_Priority:
                      type: integer
                    duration:
                      type: integer
                    durationType:
                      type: string
                    latitude:
                      type: number
                    longitude:
                      type: number
                    DC_WO_External_Id__c:
                      type: string
                    DC_Dispatch_Call_Id__c:
                      type: string
                    street:
                      type: string
                    address2:
                      type: string
                    city:
                      type: string
                    postalcode:
                      type: string
                    state:
                      type: string
                    country:
                      type: string
                    taskType:
                      type: string
                    taskTypeDescription:
                      type: string
                    DC_Property_ID__c:
                      type: string
                    DC_Data_Enrichment_Status__c:
                      type: string
                serviceAppointment:
                  type: object
                  properties:
                    earliestStartTime:
                      type: string
                    dueDate:
                      type: string
                    ServiceTerritoryName:
                      type: string
                    Status:
                      type: string
                    latitude:
                      type: number
                    longitude:
                      type: number
                    duration:
                      type: integer
                    durationType:
                      type: string
              x-examples:
                example-1:
                  workOrder:
                    workTypeName: GPON Install
                    serviceTerritoryName: Adamsville TN
                    recordTypeName: ODE Install
                    DC_Appointment_Priority: 2
                    duration: 9
                    durationType: Hours
                    latitude: 35.2359
                    longitude: -88.3906
                    DC_WO_External_Id__c: yanxxx0001
                    DC_Dispatch_Call_Id__c: y7y77yyu
                    street: 8th cross
                    address2: mysore
                    city: bangalore
                    postalcode: '560038'
                    state: Karnataka
                    country: India
                    taskType: Type of Task
                    taskTypeDescription: Description of the task type
                    DC_Property_ID__c: DC_Property_ID__c
                    DC_Data_Enrichment_Status__c: None
                  serviceAppointment:
                    earliestStartTime: '2022-04-01 07:00:00'
                    dueDate: '2022-04-23 21:20:00'
                    ServiceTerritoryName: Adamsville TN
                    Status: Unscheduled
                    latitude: 35.2359
                    longitude: -88.3906
                    duration: 9
                    durationType: Hours
            examples:
              Create Slot:
                value:
                  workOrder:
                    workTypeName: GPON Install
                    serviceTerritoryName: Adamsville TN
                    recordTypeName: ODE Install
                    DC_Appointment_Priority: 2
                    duration: 9
                    durationType: Hours
                    latitude: 35.2359
                    longitude: -88.3906
                    DC_WO_External_Id__c: yanxxx0001
                    DC_Dispatch_Call_Id__c: y7y77yyu
                    street: 8th cross
                    address2: mysore
                    city: bangalore
                    postalcode: '560038'
                    state: Karnataka
                    country: India
                    taskType: Type of Task
                    taskTypeDescription: Description of the task type
                    DC_Property_ID__c: DC_Property_ID__c
                    DC_Data_Enrichment_Status__c: None
                  serviceAppointment:
                    earliestStartTime: '2022-04-01 07:00:00'
                    dueDate: '2022-04-23 21:20:00'
                    ServiceTerritoryName: Adamsville TN
                    Status: Unscheduled
                    latitude: 35.2359
                    longitude: -88.3906
                    duration: 9
                    durationType: Hours
      description: ''
  /confirmslot:
    post:
      summary: Confirm Slot
      operationId: post-user
      responses:
        '200':
          description: User Created
          content:
            application/json:
              schema:
                type: object
                properties:
                  compositeResponse:
                    type: array
                    items:
                      type: object
                      properties:
                        body:
                          type: 'null'
                        httpHeaders:
                          type: object
                          properties: {}
                        httpStatusCode:
                          type: integer
                        referenceId:
                          type: string
                x-examples:
                  example-1:
                    compositeResponse:
                      - body: null
                        httpHeaders: {}
                        httpStatusCode: 204
                        referenceId: reference_sa
              examples:
                confirmslot:
                  value:
                    compositeResponse:
                      - body: null
                        httpHeaders: {}
                        httpStatusCode: 204
                        referenceId: reference_sa
        '400':
          description: Missing Required Information
        '409':
          description: Email Already Taken
        '':
          content:
            application/json:
              schema:
                type: object
                properties:
                  compositeResponse:
                    type: array
                    items:
                      type: object
                      properties:
                        body:
                          type: 'null'
                        httpHeaders:
                          type: object
                          properties: {}
                        httpStatusCode:
                          type: integer
                        referenceId:
                          type: string
                x-examples:
                  example-1:
                    compositeResponse:
                      - body: null
                        httpHeaders: {}
                        httpStatusCode: 204
                        referenceId: reference_sa
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                allOrNone:
                  type: boolean
                collateSubrequests:
                  type: boolean
                compositeRequest:
                  type: array
                  items:
                    type: object
                    properties:
                      body:
                        type: object
                        properties:
                          Status:
                            type: string
                          ArrivalWindowStartTime:
                            type: string
                          ArrivalWindowEndTime:
                            type: string
                      method:
                        type: string
                      referenceId:
                        type: string
                      url:
                        type: string
              x-examples:
                example-1:
                  allOrNone: true
                  collateSubrequests: false
                  compositeRequest:
                    - body:
                        Status: Unscheduled
                        ArrivalWindowStartTime: '2022-04-01T15:00:00.000+0000'
                        ArrivalWindowEndTime: '2022-04-02T00:00:00.000+0000'
                      method: PATCH
                      referenceId: reference_sa
                      url: /services/data/v50.0/sobjects/ServiceAppointment/08p8C000000H2riQAC
            examples:
              ConfirmSlot:
                value:
                  allOrNone: true
                  collateSubrequests: false
                  compositeRequest:
                    - body:
                        Status: Unscheduled
                        ArrivalWindowStartTime: '2022-04-01T15:00:00.000+0000'
                        ArrivalWindowEndTime: '2022-04-02T00:00:00.000+0000'
                      method: PATCH
                      referenceId: reference_sa
                      url: /services/data/v50.0/sobjects/ServiceAppointment/08p8C000000H2riQAC
        description: Post the necessary fields for the API to create a new user.
      description: This api is used to confirm the slot selected by user.
    parameters: []
components:
  schemas: {}
